Make clitesseract POSIX compliant

diff --git a/clitesseract b/clitesseract
--- a/clitesseract
+++ b/clitesseract
@@ -1,27 +1,28 @@
-#!/bin/bash
+#!/bin/sh
 
 
-set -o nounset
-set -o errexit
+set -o nounset  # display error and exit when referencing undefined variables
+set -o errexit  # abort script when a command exists with a non-zero status
 
 
-function main {
+main() {
     tesseract "$1" /tmp/clitess_out "${@:2}"
     cat /tmp/clitess_out* 2> /dev/null
     rm /tmp/clitess_out* 2> /dev/null
 }
 
-function showHelp {
-    echo "Tesseract command line tool."
-    echo ""
-    echo "Display the output of a Tesseract execution without worry of the \
-output file"
-    echo ""
-    echo "Usage:"
-    echo "    clitesseract <imagename> [OPTIONS] [CONFIGURATIONS]"
+showHelp() {
+    cat << EOF
+Tesseract command line tool.
+
+Display the output of a Tesseract execution without worry of the output file
+
+Usage:
+    clitesseract <imagename> [OPTIONS] [CONFIGURATIONS]
+EOF
 }
 
-if [[ $1 = "--help" || $1 = "-h" ]]; then
+if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
     showHelp
 else
     main "$@"
