Make flipscreen POSIX compliant

diff --git a/flipscreen b/flipscreen
--- a/flipscreen
+++ b/flipscreen
@@ -1,20 +1,20 @@
-#!/bin/bash
+#!/bin/sh
 
 
-set -o nounset
-set -o errexit
+set -o nounset  # display error and exit when referencing undefined variables
+set -o errexit  # abort script when a command exists with a non-zero status
 
 
 currentRotation=$(xrandr --query --verbose | grep eDP-1 | cut -b46-51)
-if [[ "$currentRotation" = "normal" ]]; then
+if [ "$currentRotation" = "normal" ]; then
     xrandr -o inverted
     xinput set-prop \
         'ELAN Touchscreen' \
         'Coordinate Transformation Matrix' \
         -1 0 1 0 -1 1 0 0 1
     # If onboard is installed then launch it
-    if command -v onboard &> /dev/null ; then
-        (onboard &) &> /dev/null
+    if command -v onboard > /dev/null 2>&1; then
+        (onboard &) > /dev/null 2>&1
     else
         echo "WARNING: onboard not installed, not able to use it"
     fi
@@ -24,5 +24,5 @@ else
         'ELAN Touchscreen' \
         'Coordinate Transformation Matrix' \
         1 0 0 0 1 0 0 0 1
-    killall onboard &> /dev/null
+    killall onboard > /dev/null 2>&1
 fi
